### ISSUE TITLE
[linshrinkage] Test target D vs R package corpcov

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#19]
It should be the same target + intensity.

**Comment by tlienart** [comment]
at first glance it looks like they're implementing yet another shrinkage intensity so either

* I mis-implemented the intensity (but it's a simple one so I doubt it)
* They do something else

I'll have to read the paper a bit more carefully. On an example I tested with their lib, I got a shrinkage of `0.82` for them and `0.75` for us. 

I've only just superficially read the paper so it may be that they argue in favour of a specific way of estimating the optimal shrinkage intensity and I missed it somehow.

**Comment by tlienart** [comment]
Ok after somewhat better read, they're doing something else indeed. I think that's what they're actually using in the implementation

![screen shot 2018-12-17 at 6 22 28 pm](https://user-images.githubusercontent.com/10897531/50072289-c9da8700-0228-11e9-81f8-81e5fe02faa9.png)

But I've still not fully wrapped my head around it: and need to check whether their equation (10) corresponds to what they're actually computing. And is equation (10) an equivalent form for that of table 2? if not what is it?

**Comment by tlienart** [comment]
Work in progress...

```julia
X = [2.0 3.0 1.0 5.0; 4.0 4.0 2.0 0.0; 2.0 2.0 4.0 1.0];
cov(X, Simple())
#  0.888889   0.666667  -0.222222  -1.33333
#  0.666667   0.666667  -0.666667  -0.333333
# -0.222222  -0.666667   1.55556   -1.66667
# -1.33333   -0.333333  -1.66667    4.66667
```

The diagonal of that should be conserved if only Target D was used but 

```R
> cov.shrink(B)
Estimating optimal shrinkage intensity lambda.var (variance vector): 0.5129 

Estimating optimal shrinkage intensity lambda (correlation matrix): 0.7277 

            [,1]       [,2]        [,3]       [,4]
[1,]  1.58980744  0.3552186 -0.09349924 -0.4687359
[2,]  0.35521861  1.4274568 -0.30690782 -0.1282174
[3,] -0.09349924 -0.3069078  2.07685923 -0.5062330
[4,] -0.46873590 -0.1282174 -0.50623302  4.3497676
```

So they shrink the variance as well.

**Comment by tlienart** [comment]
## Current summary

1. they shrink to corrected sample covariance
1. they also shrink the variance using a formula from another one of their paper, this can be suppressed for testing purposes via `lambda.var=0.0`, I'll look into this variance shrinkage thing later on
1. their formula for the optimal shrinkage of the covariance **does not** correspond to the ledoit wolf one (I don't really know why). [This paper](https://pdfs.semanticscholar.org/67b8/dbce248f73a02ce2b92c3da47f82a3dd5350.pdf) seems to explain what they're doing, though it's a bit confusing. I'll keep digging.

**Comment by mateuszbaran** [comment]
That looks like quite a lot of trouble to test against a reference implementation of a single estimator, especially when corpcor implements a different formula.
