### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#28]
I see that you've started a Documenter part which is great, is it already pushed online & can it already be added as a badge?

I could start writing docs about the `LinearShrinkageEstimator` to keep track of what equations are used where 🤦‍♂️ 

Something we could do as well is a comparative table with existing package and list what commands from our package corresponds to what command in other packages?

**Comment by mateuszbaran** [comment]
I haven't pushed the docs online yet, there is not much there at the moment. It would be great if you could add some docs :+1:.

A comparative table can be somewhat hard to do when different implementations do a bit different things but a simple list of supported algorithms with maybe some benchmarks would be nice. Corresponding commands could perhaps be a part of a "porting code from X" section?

**Comment by mateuszbaran** [comment]
I'm sorry, I didn't see your comment until now. I think each case is somewhat specific and while all of your suggestions are good, I wouldn't be too strict about having them in all docstrings. Example call could be added as a doctest: https://juliadocs.github.io/Documenter.jl/v0.21/man/doctests/#Doctests-1 . The formula is indeed quite often too complicated for a docstring.
