### ISSUE TITLE
[API] add iscentered keyword in cov

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#33]
Probably a good idea to add a `iscentered` keyword to the `cov` calls to skip the data centering if the data has already been centered?

(there's an unexported `covzm` function we could use to this effect in Statistics for the basic estimators)

**Comment by mateuszbaran** [comment]
StatsBase.jl uses a keyword argument `mean`: http://juliastats.github.io/StatsBase.jl/stable/cov.html . We could follow this and allow there `nothing` (center the data) `Array(...)` (explicitly given mean) or `:centered` (to tell that the data is already centered).
