### ISSUE TITLE
MSE benchmark of estimators

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#41]
It would be nice to have a benchmark where we generate data with a pre-assigned covariance matrix and look at the MSE of the covariance estimator and show all that on a graph for a bunch of runs with different dimensions.

**Comment by tlienart** [comment]
Ok so the branch `tl-docs` contains some experiments now which:

* generate a random covariance matrix
* sample 50 data matrix with that covariance
* recover an estimator of the covariance and compute the average MSE

results are quite interesting, basically `DiagonalCommonVariance` completely dominates

```julia
Size 15x20, best: dcv_ss_uncorr_15x20_ (0.023062498898587358; 0.0017509858255218417)
Size 20x30, best: dcv_ss_uncorr_20x30_ (0.2827035975096556; 0.020349069660928462)
Size 20x50, best: dcv_ss_uncorr_20x50_ (0.09343856241088515; 0.003532093358818667)
Size 100x1000, best: dcv_lw_corr_100x1000_ (0.00043330163971475136; 1.8164288981413426e-6)
Size 20x15, best: dcv_ss_uncorr_20x15_ (0.9975193026055088; 0.0729425102199044)
Size 30x20, best: dcv_ss_uncorr_30x20_ (0.30317651802794926; 0.019613728220031625)
Size 50x20, best: dcv_ss_uncorr_50x20_ (0.4729117871988292; 0.02299813231210621)
Size 1000x100, best: dcv_ss_uncorr_1000x100_ (0.2599732324527615; 0.0015867552636320832)
```

**Comment by tlienart** [comment]
Here with the visualisations (which I think are quite interesting!)

![bm_15x20](https://user-images.githubusercontent.com/10897531/50428413-a5a73600-090b-11e9-9576-3d0b737c81b5.png)
![bm_20x15](https://user-images.githubusercontent.com/10897531/50428414-a5a73600-090b-11e9-999d-6e28833f74c0.png)
![bm_20x30](https://user-images.githubusercontent.com/10897531/50428415-a5a73600-090b-11e9-83fc-58d8f582d838.png)
![bm_20x50](https://user-images.githubusercontent.com/10897531/50428416-a63fcc80-090b-11e9-9487-c3c30f70e3d3.png)
![bm_30x20](https://user-images.githubusercontent.com/10897531/50428417-a63fcc80-090b-11e9-9bfd-96eb02119708.png)
![bm_50x20](https://user-images.githubusercontent.com/10897531/50428418-a63fcc80-090b-11e9-9606-09e7e0754199.png)
![bm_1000x100](https://user-images.githubusercontent.com/10897531/50428420-a6d86300-090b-11e9-817f-f26249ff1640.png)
![bm_100x1000](https://user-images.githubusercontent.com/10897531/50428419-a6d86300-090b-11e9-8630-23f84c1a3488.png)

### my takeaways

* PPC (perfect positive correlation) is either really bad or badly implemented, I'll check in case it's the latter
* all methods are kind of similar though not at the same cost (so this kind of shows that nonlinear shrinkage is a bit pointless)
* DiagonalCommonVariance and CommonCovariance seem to be the best shots
* Different shrinkage methods have some impact (ss seems better) but not a whole lot.

**Comment by mateuszbaran** [comment]
Interesting results. There really seems to be something wrong with analytical nonlinear shrinkage for `n<p`. And at least some of these methods weren't designed for low MSE (for example look at Eq. (2.1) in the paper about analytical nonlinear shrinkage) so it's not surprising it sometimes turns out to be quite big.

**Comment by tlienart** [comment]
now added in the docs
