### ISSUE TITLE
[API] placement of `corrected` keyword

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#42]
At the moment:

* Simple estimator takes it within constructor `Simple(corrected=true)`
* Other estimators take it "outside" from the call to cov: `cov(X, method, corrected=true)`

we should pick one and just use that one. I reckon the second one is nice because it looks more like the base usage but the first one probably makes more sense because it's associated to the estimator. 🤷‍♂️ 

**Edit**: this will need to be updated in the docs

**Comment by mateuszbaran** [comment]
A very valid point. I'd vote for the first option (storing it in the method) and remove the second form as its only real benefit it looking more like the basic methods.
