### ISSUE TITLE
is StatsBase necessary?

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#47]
I'm in the process of refactoring a bit in order to allow `mean` to be specified as discussed in #33 all functions needed are in `Statistics` and none in `StatsBase` (at least it seems to me). 

I'm a bit confused by the two I must say, is there a reason to keep `StatsBase` in there? 

Edit: Ha maybe it's the case with weights that is relevant. I find it a bit problematic that we import `cov` from two different locations with different signatures though...

**Comment by mateuszbaran** [comment]
`StatsBase` is quite relevant, I'd like to have an extensible covariance estimation there: https://github.com/JuliaStats/StatsBase.jl/issues/439 . So we could most likely just import `cov` from `StatsBase`.

The case with weights is indeed relevant.

**Comment by tlienart** [comment]
at the risk of being dense, what's the intended difference between `Statistics.cov` and `StatsBase.cov`? is one supposed to take over at some point?

**Comment by mateuszbaran** [comment]
`StatsBase` adds a new method (this one: https://github.com/JuliaStats/StatsBase.jl/blob/88b481809cf3a4b4e381be37f4372122c2d7c361/src/cov.jl#L96 ) to the `cov` function. It supports passing weights, while methods of `cov` from `Statistics` don't. I understand that they are supposed to coexist. You can see here: https://github.com/JuliaStats/StatsBase.jl/blob/0a91ca1686b92b6c6eddbae4220468b8f05cf54f/src/StatsBase.jl#L18 that `StatsBase` indeed imports `cov` from `Statistics` to add new methods.
