### ISSUE TITLE
Simple -> SimpleEstimator

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#49]
For consistency, would it maybe be better to have

* `SimpleEstimator <: CovarianceEstimator`
* `LinearShrinkageEstimator <: CovarianceEstimator`
* `NonlinearShrinkageEstimator <: CovarianceEstimator`
* `FastMCDEstimator <: CovarianceEstimator`

etc etc ? either that or remove all `Estimators` in subtypes of `CovarianceEstimator` ?

**Comment by mateuszbaran** [comment]
It was previously suggested to drop the `Covariance` part: https://github.com/mateuszbaran/CovarianceEstimation.jl/issues/7#issuecomment-443576271 so I think it would be appropriate to drop `Estimator` as well. The names are descriptive enough without this word.

**Comment by tlienart** [comment]
ok will do a PR removing the Estimator

**Comment by mateuszbaran** [comment]
Great!
