### ISSUE TITLE
Package registration

### ISSUE THREAD

**Issue by mateuszbaran** [mateuszbaran/CovarianceEstimation.jl#60]
I think the package is good enough to register it.

@JuliaRegistrator register()

**Comment by tlienart** [comment]
Nice, did you also add install TagBot? it's pretty useful at keeping tags on the repo and the registry in synch

**Comment by mateuszbaran** [comment]
No, not yet. I'll install TagBot in a moment.

**Comment by mateuszbaran** [comment]
It's registered now :smiley: . There seems to be something wrong with version compatibility though, when I try to install it, it seems to require StatsBase at exactly 0.29.

**Comment by tlienart** [comment]
Is [this](https://discourse.julialang.org/t/switching-package-registration-systems-soon/22677/147) relevant?

**Comment by mateuszbaran** [comment]
Yes, thanks, that's probably it. I'll report it.

**Comment by mateuszbaran** [comment]
It's fixed: https://github.com/JuliaRegistries/General/pull/298 .
