### ISSUE TITLE
Should we return `Symmetric` matrices?

### ISSUE THREAD

**Issue by nickrobinson251** [mateuszbaran/CovarianceEstimation.jl#63]

**Comment by tlienart** [comment]
That seems reasonable, IIRC in a lot of places the estimators are based upon calls to the default `cov` and so properties should (?) be preserved, though we also compute the uncentered sample covariance which should be wrapped in a Symmetric wrapper. 

@mateuszbaran thoughts? also, I'm potentially happy to PR for this, haven't PRd here in a while 😉

**Comment by nickrobinson251** [comment]
Cool - go for it! (if @mateuszbaran is onboard ofc)

**Comment by mateuszbaran** [comment]
That's a good idea, although I'd be careful implementing this. Standard `cov` works for complex random variables but then the matrix is Hermitian. I haven't tested which of our estimators behave correctly for complex numbers (there is a separate issue about it, #29), `SimpleCovariance` definitely works though and some linear shrinkage estimators might work with minor modifications. The point is, if we do this, we should wrap all matrices in either `Symmetric` or `Hermitian` and `SimpleCovariance` needs to cover both cases.

I'd be happy to review a PR :slightly_smiling_face: .

**Comment by mateuszbaran** [comment]
Fixed by #64.
