### ISSUE TITLE
Trouble in getting covariance matrices for complex data

### ISSUE THREAD

**Issue by Marco-Congedo** [mateuszbaran/CovarianceEstimation.jl#65]
Hello, 
I am using CovarianceEstimation.jl to get covariance matrices without removing the mean,
also if they are just the sample covariance matrices.
I am having troubles with complex data.
I am using Julia v1.3.0
The code below is self-explaining:

```
using CovarianceEstimation, LinearAlgebra

# real data
X=randn(4, 3)
C1=(X'X)/4
C2=cov(SimpleCovariance(), X; dims = 1, mean = 0)
C1≈C2 # this is true, no problemfor real data

# complex data
Xc=randn(ComplexF64, 4, 3)
C1c=(Xc'Xc)/4
C2c=cov(SimpleCovariance(), Xc; dims = 1, mean = 0)
C1c≈C2c # this is false

# the problem appears to be with the imaginary part
C1c-C2c #gives:
3×3 Array{Complex{Float64},2}:                            
 0.0+0.0im       0.0-0.893051im  0.0-1.37915im
 0.0+0.893051im  0.0+0.0im       0.0-0.420273im
 0.0+1.37915im   0.0+0.420273im  0.0+0.0im
```
I am missing something or this is not supported?

**Comment by mateuszbaran** [comment]
Unfortunately, complex data is not supported. `SimpleCovariance` could be modified to support it but AFAIK none of the covariance shrinkage methods implemented here were designed to work with complex data.

By the way, `SimpleCovariance` is actually implemented in `StatsBase.jl`.

**Comment by Marco-Congedo** [comment]
Yeah, i guessed it does not make much sense to support complex data since shrinked estimations are only for real data. I will adapt my code. Thanks
