### ISSUE TITLE
Naming of estimators

### ISSUE THREAD

**Issue by tlienart** [mateuszbaran/CovarianceEstimation.jl#7]
At the moment there's

* `SimpleCovariance`
* `CorrectedCovariance`
* `LedoitWolfCovariance`
* `RBLWCovariance`
* `OASCovariance` (should we even have this one if it just calls RBLW?)

beyond the fact that it's not the same naming convention, it may be nice to allow several names for the same thing, e.g.:

```julia
struct LedoitWolfCovariance <: CovarianceEstimator end
const LW = LedoitWolfCovariance

struct RaoBlackwellLedoitWolfCovariance <: CovarianceEstimator end
const RBLW = RaoBlackwellLedoitWolfCovariance
```

**Comment by mateuszbaran** [comment]
`OASCovariance` and `RBLWCovariance` differ by the formula for optimal shrinkage parameter.

The naming convention definitely needs some work but `RaoBlackwellLedoitWolfCovariance` seems a bit long and I'm not sure a two-letter alias is a good idea.

**Comment by tlienart** [comment]
Sounds good, feel free to close the issue, it was more a comment than anything.

Also the code / documentation is duplicated around a bit which may be non-optimal. May be what could be better is to just write function for the different optimal shrinkages.

**Comment by mateuszbaran** [comment]
I've mostly fixed these problems in a recent API rework. I'll have to think about separation of functions that calculate the optimal shrinkage.

**Comment by tlienart** [comment]
Ok great, I'll try to follow your API to add one or two other estimators and so might give you more feedback about it

**Comment by rofinn** [comment]
FWIW, I'd probably drop the `Covariance` from the type names. Since they're already in the CovarianceEstimation package I don't think it's necessary.

**Comment by mateuszbaran** [comment]
Yes, right, `Covariance` is redundant. I'll remove it.
