### ISSUE TITLE
Biweight midcovariance as a CovarianceEstimator

### ISSUE THREAD

**Issue by tpgillam** [mateuszbaran/CovarianceEstimation.jl#80]
Hello! We've written an implementation of [biweight midcovariance](https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/biwmidc.htm) — would you be happy to receive a PR to integrate it into CovarianceEstimation? If so I'll start work on it.

This issue seems related, and proposes adding them to `StatsBase`: https://github.com/JuliaStats/StatsBase.jl/issues/569 . But to me it seems like it would be better to put a fairly specialised method like this in this package, rather than `StatsBase`?

**Comment by tlienart** [comment]
> would you be happy to receive a PR to integrate it

Yes; please kindly also provide a reference implementation as well if there is one or tests with respect to a reference implementation (e.g. if there's a credible R package that does this). 

Ideally the PR for a new method should eventually contain:

* the actual method
* clear comments in the method clarifying what is done + the computational complexity of the method
* an update to the docs clarifying what the method does / how it works + links to the relevant literature
* tests to ensure the method works
* tests to compare the method to a reference implementation if there is one somewhere

Thanks!

PS: you can also open a draft PR and we can try to help you push it along
PPS: with respect to reference implementation; if there is one but in a proprietary software like Matlab; what you can do is have a few example cases that you evaluate with both this package and Matlab and ensure that the results are comparable (this is what is done in our tests for some of the reference implementation).

**Comment by tpgillam** [comment]
Excellent, thank you for the pointers.

The reference implementations I'm aware of are:

* [astropy](https://docs.astropy.org/en/stable/api/astropy.stats.biweight.biweight_midcovariance.html) (Python)
* NIST [Dataplot](https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/biwmidc.htm)

I've never used dataplot before, so my preference would be to use astropy for computing the references, if that suits.

**Comment by tlienart** [comment]
astropy is great and it's BSD3 so no license issues :+1:
